// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type CreateEventBreakerRulesetRequest struct {
	// The consumer group to which this instance belongs. Defaults to 'Cribl'.
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
	// New Event Breaker Ruleset object
	EventBreakerRuleset shared.EventBreakerRuleset `request:"mediaType=application/json"`
}

func (o *CreateEventBreakerRulesetRequest) GetGroupID() string {
	if o == nil {
		return ""
	}
	return o.GroupID
}

func (o *CreateEventBreakerRulesetRequest) GetEventBreakerRuleset() shared.EventBreakerRuleset {
	if o == nil {
		return shared.EventBreakerRuleset{}
	}
	return o.EventBreakerRuleset
}

// CreateEventBreakerRulesetResponseBody - a list of Event Breaker Ruleset objects
type CreateEventBreakerRulesetResponseBody struct {
}

type CreateEventBreakerRulesetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Event Breaker Ruleset objects
	Object *CreateEventBreakerRulesetResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *CreateEventBreakerRulesetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateEventBreakerRulesetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateEventBreakerRulesetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateEventBreakerRulesetResponse) GetObject() *CreateEventBreakerRulesetResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *CreateEventBreakerRulesetResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
