// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

// CreateVersionPushResponseBody - a list of any objects
type CreateVersionPushResponseBody struct {
	Items []map[string]any `json:"items,omitempty"`
}

func (o *CreateVersionPushResponseBody) GetItems() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateVersionPushResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of any objects
	Object *CreateVersionPushResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *CreateVersionPushResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateVersionPushResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateVersionPushResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateVersionPushResponse) GetObject() *CreateVersionPushResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *CreateVersionPushResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
