// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

// CreateSearchEventBreakerPreviewResponseBody - a list of PreviewResponseBody objects
type CreateSearchEventBreakerPreviewResponseBody struct {
	Items []shared.PreviewResponseBody `json:"items,omitempty"`
}

func (c *CreateSearchEventBreakerPreviewResponseBody) GetItems() []shared.PreviewResponseBody {
	if c == nil {
		return nil
	}
	return c.Items
}

type CreateSearchEventBreakerPreviewResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of PreviewResponseBody objects
	Object *CreateSearchEventBreakerPreviewResponseBody
	// Unexpected error
	Error *shared.Error
}

func (c *CreateSearchEventBreakerPreviewResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateSearchEventBreakerPreviewResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateSearchEventBreakerPreviewResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateSearchEventBreakerPreviewResponse) GetObject() *CreateSearchEventBreakerPreviewResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}

func (c *CreateSearchEventBreakerPreviewResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
