// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type CreateBreakersByPackRequest struct {
	// pack ID to POST
	Pack string `pathParam:"style=simple,explode=false,name=pack"`
	// group ID to GET
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
	// Pipeline object to be updated in specified Project
	EventBreakerRuleset shared.EventBreakerRuleset `request:"mediaType=application/json"`
}

func (o *CreateBreakersByPackRequest) GetPack() string {
	if o == nil {
		return ""
	}
	return o.Pack
}

func (o *CreateBreakersByPackRequest) GetGroupID() string {
	if o == nil {
		return ""
	}
	return o.GroupID
}

func (o *CreateBreakersByPackRequest) GetEventBreakerRuleset() shared.EventBreakerRuleset {
	if o == nil {
		return shared.EventBreakerRuleset{}
	}
	return o.EventBreakerRuleset
}

// CreateBreakersByPackResponseBody - a list of Routes objects
type CreateBreakersByPackResponseBody struct {
	Items []shared.Routes `json:"items,omitempty"`
}

func (o *CreateBreakersByPackResponseBody) GetItems() []shared.Routes {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateBreakersByPackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Routes objects
	Object *CreateBreakersByPackResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *CreateBreakersByPackResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateBreakersByPackResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateBreakersByPackResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateBreakersByPackResponse) GetObject() *CreateBreakersByPackResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *CreateBreakersByPackResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
