// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

// CreateSystemMetricsQueryResponseBody - a list of Response objects
type CreateSystemMetricsQueryResponseBody struct {
	Items []map[string]any `json:"items,omitempty"`
}

func (o *CreateSystemMetricsQueryResponseBody) GetItems() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateSystemMetricsQueryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Response objects
	Object *CreateSystemMetricsQueryResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *CreateSystemMetricsQueryResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateSystemMetricsQueryResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateSystemMetricsQueryResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateSystemMetricsQueryResponse) GetObject() *CreateSystemMetricsQueryResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *CreateSystemMetricsQueryResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
