// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

// CreateLibExpressionResponseBody - a list of ExprLibEntry objects
type CreateLibExpressionResponseBody struct {
	Items []shared.ExprLibEntry `json:"items,omitempty"`
}

func (o *CreateLibExpressionResponseBody) GetItems() []shared.ExprLibEntry {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateLibExpressionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of ExprLibEntry objects
	Object *CreateLibExpressionResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *CreateLibExpressionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateLibExpressionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateLibExpressionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateLibExpressionResponse) GetObject() *CreateLibExpressionResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *CreateLibExpressionResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
