// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type CreateSystemDistributedUpgradeByGroupRequest struct {
	// Group to upgrade
	Group string `pathParam:"style=simple,explode=false,name=group"`
	// distributedUpgrade object
	DistributedUpgradeRequest shared.DistributedUpgradeRequest `request:"mediaType=application/json"`
}

func (c *CreateSystemDistributedUpgradeByGroupRequest) GetGroup() string {
	if c == nil {
		return ""
	}
	return c.Group
}

func (c *CreateSystemDistributedUpgradeByGroupRequest) GetDistributedUpgradeRequest() shared.DistributedUpgradeRequest {
	if c == nil {
		return shared.DistributedUpgradeRequest{}
	}
	return c.DistributedUpgradeRequest
}

// CreateSystemDistributedUpgradeByGroupResponseBody - a list of string objects
type CreateSystemDistributedUpgradeByGroupResponseBody struct {
	Items []string `json:"items,omitempty"`
}

func (c *CreateSystemDistributedUpgradeByGroupResponseBody) GetItems() []string {
	if c == nil {
		return nil
	}
	return c.Items
}

type CreateSystemDistributedUpgradeByGroupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of string objects
	Object *CreateSystemDistributedUpgradeByGroupResponseBody
	// Unexpected error
	Error *shared.Error
}

func (c *CreateSystemDistributedUpgradeByGroupResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateSystemDistributedUpgradeByGroupResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateSystemDistributedUpgradeByGroupResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateSystemDistributedUpgradeByGroupResponse) GetObject() *CreateSystemDistributedUpgradeByGroupResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}

func (c *CreateSystemDistributedUpgradeByGroupResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
