// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type DeleteAuthUsersInvalidationByIDRequest struct {
	// ID of user to reenable
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteAuthUsersInvalidationByIDRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

// DeleteAuthUsersInvalidationByIDResponseBody - a list of any objects
type DeleteAuthUsersInvalidationByIDResponseBody struct {
	Items []map[string]any `json:"items,omitempty"`
}

func (d *DeleteAuthUsersInvalidationByIDResponseBody) GetItems() []map[string]any {
	if d == nil {
		return nil
	}
	return d.Items
}

type DeleteAuthUsersInvalidationByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of any objects
	Object *DeleteAuthUsersInvalidationByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (d *DeleteAuthUsersInvalidationByIDResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteAuthUsersInvalidationByIDResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteAuthUsersInvalidationByIDResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteAuthUsersInvalidationByIDResponse) GetObject() *DeleteAuthUsersInvalidationByIDResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}

func (d *DeleteAuthUsersInvalidationByIDResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
