// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type DeleteEdgeAppscopeProcessesByPidRequest struct {
	// config string required
	Pid string `pathParam:"style=simple,explode=false,name=pid"`
}

func (d *DeleteEdgeAppscopeProcessesByPidRequest) GetPid() string {
	if d == nil {
		return ""
	}
	return d.Pid
}

// DeleteEdgeAppscopeProcessesByPidResponseBody - a list of AppScopeProcess objects
type DeleteEdgeAppscopeProcessesByPidResponseBody struct {
	Items []shared.AppScopeProcess `json:"items,omitempty"`
}

func (d *DeleteEdgeAppscopeProcessesByPidResponseBody) GetItems() []shared.AppScopeProcess {
	if d == nil {
		return nil
	}
	return d.Items
}

type DeleteEdgeAppscopeProcessesByPidResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of AppScopeProcess objects
	Object *DeleteEdgeAppscopeProcessesByPidResponseBody
	// Unexpected error
	Error *shared.Error
}

func (d *DeleteEdgeAppscopeProcessesByPidResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteEdgeAppscopeProcessesByPidResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteEdgeAppscopeProcessesByPidResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteEdgeAppscopeProcessesByPidResponse) GetObject() *DeleteEdgeAppscopeProcessesByPidResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}

func (d *DeleteEdgeAppscopeProcessesByPidResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
