// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type DeleteSystemDiagRequest struct {
	// Diag bundle path
	Path string `queryParam:"style=form,explode=true,name=path"`
}

func (d *DeleteSystemDiagRequest) GetPath() string {
	if d == nil {
		return ""
	}
	return d.Path
}

// DeleteSystemDiagResponseBody - a list of any objects
type DeleteSystemDiagResponseBody struct {
	Items []map[string]any `json:"items,omitempty"`
}

func (d *DeleteSystemDiagResponseBody) GetItems() []map[string]any {
	if d == nil {
		return nil
	}
	return d.Items
}

type DeleteSystemDiagResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of any objects
	Object *DeleteSystemDiagResponseBody
	// Unexpected error
	Error *shared.Error
}

func (d *DeleteSystemDiagResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteSystemDiagResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteSystemDiagResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteSystemDiagResponse) GetObject() *DeleteSystemDiagResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}

func (d *DeleteSystemDiagResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
