// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type DeleteRoutesByPackAndIDRequest struct {
	// Unique ID to DELETE for pack
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// pack ID to DELETE
	Pack string `pathParam:"style=simple,explode=false,name=pack"`
	// group Id
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
}

func (o *DeleteRoutesByPackAndIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DeleteRoutesByPackAndIDRequest) GetPack() string {
	if o == nil {
		return ""
	}
	return o.Pack
}

func (o *DeleteRoutesByPackAndIDRequest) GetGroupID() string {
	if o == nil {
		return ""
	}
	return o.GroupID
}

// DeleteRoutesByPackAndIDResponseBody - a list of Pipeline objects
type DeleteRoutesByPackAndIDResponseBody struct {
	Items []shared.Pipeline `json:"items,omitempty"`
}

func (o *DeleteRoutesByPackAndIDResponseBody) GetItems() []shared.Pipeline {
	if o == nil {
		return nil
	}
	return o.Items
}

type DeleteRoutesByPackAndIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Pipeline objects
	Object *DeleteRoutesByPackAndIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *DeleteRoutesByPackAndIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteRoutesByPackAndIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteRoutesByPackAndIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteRoutesByPackAndIDResponse) GetObject() *DeleteRoutesByPackAndIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *DeleteRoutesByPackAndIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
