// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type DeleteSystemLookupsByPackAndIDRequest struct {
	// Unique ID to DELETE for pack
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// pack ID to DELETE
	Pack string `pathParam:"style=simple,explode=false,name=pack"`
	// group Id
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
}

func (d *DeleteSystemLookupsByPackAndIDRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeleteSystemLookupsByPackAndIDRequest) GetPack() string {
	if d == nil {
		return ""
	}
	return d.Pack
}

func (d *DeleteSystemLookupsByPackAndIDRequest) GetGroupID() string {
	if d == nil {
		return ""
	}
	return d.GroupID
}

// DeleteSystemLookupsByPackAndIDResponseBody - a list of Pipeline objects
type DeleteSystemLookupsByPackAndIDResponseBody struct {
	Items []shared.Pipeline `json:"items,omitempty"`
}

func (d *DeleteSystemLookupsByPackAndIDResponseBody) GetItems() []shared.Pipeline {
	if d == nil {
		return nil
	}
	return d.Items
}

type DeleteSystemLookupsByPackAndIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Pipeline objects
	Object *DeleteSystemLookupsByPackAndIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (d *DeleteSystemLookupsByPackAndIDResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteSystemLookupsByPackAndIDResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteSystemLookupsByPackAndIDResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteSystemLookupsByPackAndIDResponse) GetObject() *DeleteSystemLookupsByPackAndIDResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}

func (d *DeleteSystemLookupsByPackAndIDResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
