// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type DeleteDefaultLakeLakehouseByIDRequest struct {
	// The ID of the lakehouse to delete
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteDefaultLakeLakehouseByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// DeleteDefaultLakeLakehouseByIDResponseBody - a list of Lakehouse objects
type DeleteDefaultLakeLakehouseByIDResponseBody struct {
	Items []shared.Lakehouse `json:"items,omitempty"`
}

func (o *DeleteDefaultLakeLakehouseByIDResponseBody) GetItems() []shared.Lakehouse {
	if o == nil {
		return nil
	}
	return o.Items
}

type DeleteDefaultLakeLakehouseByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Lakehouse objects
	Object *DeleteDefaultLakeLakehouseByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *DeleteDefaultLakeLakehouseByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteDefaultLakeLakehouseByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteDefaultLakeLakehouseByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteDefaultLakeLakehouseByIDResponse) GetObject() *DeleteDefaultLakeLakehouseByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *DeleteDefaultLakeLakehouseByIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
