// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type DeleteDatasetProviderTypeByIDRequest struct {
	// Unique ID to DELETE
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteDatasetProviderTypeByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// DeleteDatasetProviderTypeByIDResponseBody - a list of DatasetProviderType objects
type DeleteDatasetProviderTypeByIDResponseBody struct {
	Items []shared.DatasetProviderType `json:"items,omitempty"`
}

func (o *DeleteDatasetProviderTypeByIDResponseBody) GetItems() []shared.DatasetProviderType {
	if o == nil {
		return nil
	}
	return o.Items
}

type DeleteDatasetProviderTypeByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of DatasetProviderType objects
	Object *DeleteDatasetProviderTypeByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *DeleteDatasetProviderTypeByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteDatasetProviderTypeByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteDatasetProviderTypeByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteDatasetProviderTypeByIDResponse) GetObject() *DeleteDatasetProviderTypeByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *DeleteDatasetProviderTypeByIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
