// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type DeleteProjectByIDRequest struct {
	// Unique ID to DELETE
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The consumer group to which this instance belongs. Defaults to 'Cribl'.
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
}

func (o *DeleteProjectByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DeleteProjectByIDRequest) GetGroupID() string {
	if o == nil {
		return ""
	}
	return o.GroupID
}

// DeleteProjectByIDResponseBody - a list of Project objects
type DeleteProjectByIDResponseBody struct {
	Items []shared.ProjectConfig `json:"items,omitempty"`
}

func (o *DeleteProjectByIDResponseBody) GetItems() []shared.ProjectConfig {
	if o == nil {
		return nil
	}
	return o.Items
}

type DeleteProjectByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Project objects
	Object *DeleteProjectByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *DeleteProjectByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteProjectByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteProjectByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteProjectByIDResponse) GetObject() *DeleteProjectByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *DeleteProjectByIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
