// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type DeleteSystemDiagRequest struct {
	// Diag bundle path
	Path string `queryParam:"style=form,explode=true,name=path"`
}

func (o *DeleteSystemDiagRequest) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}

// DeleteSystemDiagResponseBody - a list of any objects
type DeleteSystemDiagResponseBody struct {
	Items []map[string]any `json:"items,omitempty"`
}

func (o *DeleteSystemDiagResponseBody) GetItems() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Items
}

type DeleteSystemDiagResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of any objects
	Object *DeleteSystemDiagResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *DeleteSystemDiagResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteSystemDiagResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteSystemDiagResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteSystemDiagResponse) GetObject() *DeleteSystemDiagResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *DeleteSystemDiagResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
