// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type DeleteUserByIDRequest struct {
	// Unique ID to DELETE
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteUserByIDRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

// DeleteUserByIDResponseBody - a list of User objects
type DeleteUserByIDResponseBody struct {
	Items []shared.User `json:"items,omitempty"`
}

func (d *DeleteUserByIDResponseBody) GetItems() []shared.User {
	if d == nil {
		return nil
	}
	return d.Items
}

type DeleteUserByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of User objects
	Object *DeleteUserByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (d *DeleteUserByIDResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteUserByIDResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteUserByIDResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteUserByIDResponse) GetObject() *DeleteUserByIDResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}

func (d *DeleteUserByIDResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
