// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type DeleteRestSecretByIDRequest struct {
	// Unique ID to DELETE
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteRestSecretByIDRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

// DeleteRestSecretByIDResponseBody - a list of RestSecret objects
type DeleteRestSecretByIDResponseBody struct {
	Items []shared.RestSecret `json:"items,omitempty"`
}

func (d *DeleteRestSecretByIDResponseBody) GetItems() []shared.RestSecret {
	if d == nil {
		return nil
	}
	return d.Items
}

type DeleteRestSecretByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of RestSecret objects
	Object *DeleteRestSecretByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (d *DeleteRestSecretByIDResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteRestSecretByIDResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteRestSecretByIDResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteRestSecretByIDResponse) GetObject() *DeleteRestSecretByIDResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}

func (d *DeleteRestSecretByIDResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
