// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

// GetCriblLakeDatasetByLakeIDLakeID - lake id that contains the Datasets
type GetCriblLakeDatasetByLakeIDLakeID string

const (
	GetCriblLakeDatasetByLakeIDLakeIDDefault GetCriblLakeDatasetByLakeIDLakeID = "default"
)

func (e GetCriblLakeDatasetByLakeIDLakeID) ToPointer() *GetCriblLakeDatasetByLakeIDLakeID {
	return &e
}
func (e *GetCriblLakeDatasetByLakeIDLakeID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "default":
		*e = GetCriblLakeDatasetByLakeIDLakeID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetCriblLakeDatasetByLakeIDLakeID: %v", v)
	}
}

type GetCriblLakeDatasetByLakeIDRequest struct {
	// lake id that contains the Datasets
	LakeID GetCriblLakeDatasetByLakeIDLakeID `pathParam:"style=simple,explode=false,name=lakeId"`
}

func (o *GetCriblLakeDatasetByLakeIDRequest) GetLakeID() GetCriblLakeDatasetByLakeIDLakeID {
	if o == nil {
		return GetCriblLakeDatasetByLakeIDLakeID("")
	}
	return o.LakeID
}

// GetCriblLakeDatasetByLakeIDResponseBody - a list of CriblLakeDataset objects
type GetCriblLakeDatasetByLakeIDResponseBody struct {
	Items []shared.CriblLakeDataset `json:"items,omitempty"`
}

func (o *GetCriblLakeDatasetByLakeIDResponseBody) GetItems() []shared.CriblLakeDataset {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetCriblLakeDatasetByLakeIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of CriblLakeDataset objects
	Object *GetCriblLakeDatasetByLakeIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *GetCriblLakeDatasetByLakeIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetCriblLakeDatasetByLakeIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetCriblLakeDatasetByLakeIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetCriblLakeDatasetByLakeIDResponse) GetObject() *GetCriblLakeDatasetByLakeIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *GetCriblLakeDatasetByLakeIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
