// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type GetDatasetProviderByIDRequest struct {
	// Unique ID to GET
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetDatasetProviderByIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

// GetDatasetProviderByIDResponseBody - a list of DatasetProvider objects
type GetDatasetProviderByIDResponseBody struct {
	Items []shared.GenericProvider `json:"items,omitempty"`
}

func (g *GetDatasetProviderByIDResponseBody) GetItems() []shared.GenericProvider {
	if g == nil {
		return nil
	}
	return g.Items
}

type GetDatasetProviderByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of DatasetProvider objects
	Object *GetDatasetProviderByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (g *GetDatasetProviderByIDResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetDatasetProviderByIDResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetDatasetProviderByIDResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetDatasetProviderByIDResponse) GetObject() *GetDatasetProviderByIDResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetDatasetProviderByIDResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
