// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

// GetEdgeContainersResponseBody - a list of Container objects
type GetEdgeContainersResponseBody struct {
	Items []shared.Container `json:"items,omitempty"`
}

func (g *GetEdgeContainersResponseBody) GetItems() []shared.Container {
	if g == nil {
		return nil
	}
	return g.Items
}

type GetEdgeContainersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Container objects
	Object *GetEdgeContainersResponseBody
	// Unexpected error
	Error *shared.Error
}

func (g *GetEdgeContainersResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetEdgeContainersResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetEdgeContainersResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetEdgeContainersResponse) GetObject() *GetEdgeContainersResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetEdgeContainersResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
