// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

// GetEdgeFileinspectResponseBody - a list of EdgeFileInspectResponse objects
type GetEdgeFileinspectResponseBody struct {
	Items []shared.EdgeFileInspectResponse `json:"items,omitempty"`
}

func (o *GetEdgeFileinspectResponseBody) GetItems() []shared.EdgeFileInspectResponse {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetEdgeFileinspectResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of EdgeFileInspectResponse objects
	Object *GetEdgeFileinspectResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *GetEdgeFileinspectResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetEdgeFileinspectResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetEdgeFileinspectResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetEdgeFileinspectResponse) GetObject() *GetEdgeFileinspectResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *GetEdgeFileinspectResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
