// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type GetNotificationByIDRequest struct {
	// Unique ID to GET
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetNotificationByIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

// GetNotificationByIDResponseBody - a list of Notification objects
type GetNotificationByIDResponseBody struct {
	Items []shared.Notification `json:"items,omitempty"`
}

func (g *GetNotificationByIDResponseBody) GetItems() []shared.Notification {
	if g == nil {
		return nil
	}
	return g.Items
}

type GetNotificationByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Notification objects
	Object *GetNotificationByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (g *GetNotificationByIDResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetNotificationByIDResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetNotificationByIDResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetNotificationByIDResponse) GetObject() *GetNotificationByIDResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetNotificationByIDResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
