// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type GetPipelineByPackRequest struct {
	// pack ID to GET
	Pack string `pathParam:"style=simple,explode=false,name=pack"`
	// The consumer group to which this instance belongs. Defaults to 'Cribl'.
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
}

func (o *GetPipelineByPackRequest) GetPack() string {
	if o == nil {
		return ""
	}
	return o.Pack
}

func (o *GetPipelineByPackRequest) GetGroupID() string {
	if o == nil {
		return ""
	}
	return o.GroupID
}

// GetPipelineByPackResponseBody - a list of Pipeline objects
type GetPipelineByPackResponseBody struct {
	Items []shared.Pipeline `json:"items,omitempty"`
}

func (o *GetPipelineByPackResponseBody) GetItems() []shared.Pipeline {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetPipelineByPackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Pipeline objects
	Object *GetPipelineByPackResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *GetPipelineByPackResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetPipelineByPackResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetPipelineByPackResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetPipelineByPackResponse) GetObject() *GetPipelineByPackResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *GetPipelineByPackResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
