// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

// GetSystemLogsResponseBody - a list of LogFileInfo objects
type GetSystemLogsResponseBody struct {
	Items []shared.LogFileInfo `json:"items,omitempty"`
}

func (g *GetSystemLogsResponseBody) GetItems() []shared.LogFileInfo {
	if g == nil {
		return nil
	}
	return g.Items
}

type GetSystemLogsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of LogFileInfo objects
	Object *GetSystemLogsResponseBody
	// Unexpected error
	Error *shared.Error
}

func (g *GetSystemLogsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetSystemLogsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetSystemLogsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetSystemLogsResponse) GetObject() *GetSystemLogsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetSystemLogsResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
