// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type GetSearchMacroByIDRequest struct {
	// Unique ID to GET
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetSearchMacroByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetSearchMacroByIDResponseBody - a list of SearchMacro objects
type GetSearchMacroByIDResponseBody struct {
	Items []shared.SearchMacro `json:"items,omitempty"`
}

func (o *GetSearchMacroByIDResponseBody) GetItems() []shared.SearchMacro {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetSearchMacroByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of SearchMacro objects
	Object *GetSearchMacroByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *GetSearchMacroByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSearchMacroByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSearchMacroByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSearchMacroByIDResponse) GetObject() *GetSearchMacroByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *GetSearchMacroByIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
