// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type GetSubscriptionByProjectIDRequest struct {
	// Project Id
	ProjectID string `pathParam:"style=simple,explode=false,name=projectId"`
}

func (g *GetSubscriptionByProjectIDRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

// GetSubscriptionByProjectIDResponseBody - a list of Subscription objects
type GetSubscriptionByProjectIDResponseBody struct {
	Items []shared.Subscription `json:"items,omitempty"`
}

func (g *GetSubscriptionByProjectIDResponseBody) GetItems() []shared.Subscription {
	if g == nil {
		return nil
	}
	return g.Items
}

type GetSubscriptionByProjectIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Subscription objects
	Object *GetSubscriptionByProjectIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (g *GetSubscriptionByProjectIDResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetSubscriptionByProjectIDResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetSubscriptionByProjectIDResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetSubscriptionByProjectIDResponse) GetObject() *GetSubscriptionByProjectIDResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetSubscriptionByProjectIDResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
