// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type ListLibSchemasRequest struct {
	// The consumer group to which this instance belongs. Defaults to 'Cribl'.
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
}

func (l *ListLibSchemasRequest) GetGroupID() string {
	if l == nil {
		return ""
	}
	return l.GroupID
}

// ListLibSchemasResponseBody - a list of Schema objects
type ListLibSchemasResponseBody struct {
	Items []shared.SchemaLibEntry `json:"items,omitempty"`
}

func (l *ListLibSchemasResponseBody) GetItems() []shared.SchemaLibEntry {
	if l == nil {
		return nil
	}
	return l.Items
}

type ListLibSchemasResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Schema objects
	Object *ListLibSchemasResponseBody
	// Unexpected error
	Error *shared.Error
}

func (l *ListLibSchemasResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListLibSchemasResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListLibSchemasResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListLibSchemasResponse) GetObject() *ListLibSchemasResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}

func (l *ListLibSchemasResponse) GetError() *shared.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
