// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

// ListDatasetProviderResponseBody - a list of DatasetProvider objects
type ListDatasetProviderResponseBody struct {
	Items []any `json:"items,omitempty"`
}

func (o *ListDatasetProviderResponseBody) GetItems() []any {
	if o == nil {
		return nil
	}
	return o.Items
}

type ListDatasetProviderResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of DatasetProvider objects
	Object *ListDatasetProviderResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *ListDatasetProviderResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListDatasetProviderResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListDatasetProviderResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListDatasetProviderResponse) GetObject() *ListDatasetProviderResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *ListDatasetProviderResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
