// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type UpdateSchemaLibByPackAndIDRequest struct {
	// Unique ID to PATCH for pack
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// pack ID to PATCH
	Pack string `pathParam:"style=simple,explode=false,name=pack"`
	// Schema object to be updated
	SchemaLibEntry shared.SchemaLibEntry `request:"mediaType=application/json"`
}

func (u *UpdateSchemaLibByPackAndIDRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateSchemaLibByPackAndIDRequest) GetPack() string {
	if u == nil {
		return ""
	}
	return u.Pack
}

func (u *UpdateSchemaLibByPackAndIDRequest) GetSchemaLibEntry() shared.SchemaLibEntry {
	if u == nil {
		return shared.SchemaLibEntry{}
	}
	return u.SchemaLibEntry
}

// UpdateSchemaLibByPackAndIDResponseBody - a list of Schema objects
type UpdateSchemaLibByPackAndIDResponseBody struct {
	Items []shared.SchemaLibEntry `json:"items,omitempty"`
}

func (u *UpdateSchemaLibByPackAndIDResponseBody) GetItems() []shared.SchemaLibEntry {
	if u == nil {
		return nil
	}
	return u.Items
}

type UpdateSchemaLibByPackAndIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Schema objects
	Object *UpdateSchemaLibByPackAndIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (u *UpdateSchemaLibByPackAndIDResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateSchemaLibByPackAndIDResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateSchemaLibByPackAndIDResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateSchemaLibByPackAndIDResponse) GetObject() *UpdateSchemaLibByPackAndIDResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}

func (u *UpdateSchemaLibByPackAndIDResponse) GetError() *shared.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
