// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type UpdateSavedQueryByIDRequest struct {
	// Unique ID to PATCH
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// SavedQuery object to be updated
	SavedQuery shared.SavedQuery `request:"mediaType=application/json"`
}

func (u *UpdateSavedQueryByIDRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateSavedQueryByIDRequest) GetSavedQuery() shared.SavedQuery {
	if u == nil {
		return shared.SavedQuery{}
	}
	return u.SavedQuery
}

// UpdateSavedQueryByIDResponseBody - a list of SavedQuery objects
type UpdateSavedQueryByIDResponseBody struct {
	Items []shared.SavedQuery `json:"items,omitempty"`
}

func (u *UpdateSavedQueryByIDResponseBody) GetItems() []shared.SavedQuery {
	if u == nil {
		return nil
	}
	return u.Items
}

type UpdateSavedQueryByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of SavedQuery objects
	Object *UpdateSavedQueryByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (u *UpdateSavedQueryByIDResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateSavedQueryByIDResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateSavedQueryByIDResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateSavedQueryByIDResponse) GetObject() *UpdateSavedQueryByIDResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}

func (u *UpdateSavedQueryByIDResponse) GetError() *shared.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
