// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type UpdateProfilerItemByIDRequest struct {
	// Unique ID to PATCH
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// ProfilerItem object to be updated
	ProfilerItem shared.ProfilerItem `request:"mediaType=application/json"`
}

func (u *UpdateProfilerItemByIDRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateProfilerItemByIDRequest) GetProfilerItem() shared.ProfilerItem {
	if u == nil {
		return shared.ProfilerItem{}
	}
	return u.ProfilerItem
}

// UpdateProfilerItemByIDResponseBody - a list of ProfilerItem objects
type UpdateProfilerItemByIDResponseBody struct {
	Items []shared.ProfilerItem `json:"items,omitempty"`
}

func (u *UpdateProfilerItemByIDResponseBody) GetItems() []shared.ProfilerItem {
	if u == nil {
		return nil
	}
	return u.Items
}

type UpdateProfilerItemByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of ProfilerItem objects
	Object *UpdateProfilerItemByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (u *UpdateProfilerItemByIDResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateProfilerItemByIDResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateProfilerItemByIDResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateProfilerItemByIDResponse) GetObject() *UpdateProfilerItemByIDResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}

func (u *UpdateProfilerItemByIDResponse) GetError() *shared.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
