// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type UpdateBreakersByPackAndIDRequest struct {
	// Unique ID to PATCH for pack
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// pack ID to POST
	Pack string `pathParam:"style=simple,explode=false,name=pack"`
	// group Id
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
	// Pipeline object to be updated in specified Project
	EventBreakerRuleset shared.EventBreakerRuleset `request:"mediaType=application/json"`
}

func (u *UpdateBreakersByPackAndIDRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateBreakersByPackAndIDRequest) GetPack() string {
	if u == nil {
		return ""
	}
	return u.Pack
}

func (u *UpdateBreakersByPackAndIDRequest) GetGroupID() string {
	if u == nil {
		return ""
	}
	return u.GroupID
}

func (u *UpdateBreakersByPackAndIDRequest) GetEventBreakerRuleset() shared.EventBreakerRuleset {
	if u == nil {
		return shared.EventBreakerRuleset{}
	}
	return u.EventBreakerRuleset
}

// UpdateBreakersByPackAndIDResponseBody - a list of Routes objects
type UpdateBreakersByPackAndIDResponseBody struct {
	Items []shared.Routes `json:"items,omitempty"`
}

func (u *UpdateBreakersByPackAndIDResponseBody) GetItems() []shared.Routes {
	if u == nil {
		return nil
	}
	return u.Items
}

type UpdateBreakersByPackAndIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Routes objects
	Object *UpdateBreakersByPackAndIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (u *UpdateBreakersByPackAndIDResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateBreakersByPackAndIDResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateBreakersByPackAndIDResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateBreakersByPackAndIDResponse) GetObject() *UpdateBreakersByPackAndIDResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}

func (u *UpdateBreakersByPackAndIDResponse) GetError() *shared.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
