// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type UpdateSystemInputsByPackRequest struct {
	// pack ID to PATCH
	Pack     string `pathParam:"style=simple,explode=false,name=pack"`
	Disabled *bool  `queryParam:"style=form,explode=true,name=disabled"`
	// group Id
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
	// Unique ID to PATCH for pack source
	ID    string       `pathParam:"style=simple,explode=false,name=id"`
	Input shared.Input `request:"mediaType=application/json"`
}

func (u *UpdateSystemInputsByPackRequest) GetPack() string {
	if u == nil {
		return ""
	}
	return u.Pack
}

func (u *UpdateSystemInputsByPackRequest) GetDisabled() *bool {
	if u == nil {
		return nil
	}
	return u.Disabled
}

func (u *UpdateSystemInputsByPackRequest) GetGroupID() string {
	if u == nil {
		return ""
	}
	return u.GroupID
}

func (u *UpdateSystemInputsByPackRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateSystemInputsByPackRequest) GetInput() shared.Input {
	if u == nil {
		return shared.Input{}
	}
	return u.Input
}

// UpdateSystemInputsByPackResponseBody - a list of Pipeline objects
type UpdateSystemInputsByPackResponseBody struct {
	Items []shared.Pipeline `json:"items,omitempty"`
}

func (u *UpdateSystemInputsByPackResponseBody) GetItems() []shared.Pipeline {
	if u == nil {
		return nil
	}
	return u.Items
}

type UpdateSystemInputsByPackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Pipeline objects
	Object *UpdateSystemInputsByPackResponseBody
	// Unexpected error
	Error *shared.Error
}

func (u *UpdateSystemInputsByPackResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateSystemInputsByPackResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateSystemInputsByPackResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateSystemInputsByPackResponse) GetObject() *UpdateSystemInputsByPackResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}

func (u *UpdateSystemInputsByPackResponse) GetError() *shared.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
