// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

// UpdateSystemSettingsConfResponseBody - a list of SystemSettings objects
type UpdateSystemSettingsConfResponseBody struct {
	Items []shared.SystemSettings `json:"items,omitempty"`
}

func (u *UpdateSystemSettingsConfResponseBody) GetItems() []shared.SystemSettings {
	if u == nil {
		return nil
	}
	return u.Items
}

type UpdateSystemSettingsConfResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of SystemSettings objects
	Object *UpdateSystemSettingsConfResponseBody
	// Unexpected error
	Error *shared.Error
}

func (u *UpdateSystemSettingsConfResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateSystemSettingsConfResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateSystemSettingsConfResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateSystemSettingsConfResponse) GetObject() *UpdateSystemSettingsConfResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}

func (u *UpdateSystemSettingsConfResponse) GetError() *shared.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
