// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type UpdateDataSampleByIDRequest struct {
	// Unique ID to PATCH
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// DataSample object to be updated
	DataSample shared.DataSample `request:"mediaType=application/json"`
}

func (u *UpdateDataSampleByIDRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateDataSampleByIDRequest) GetDataSample() shared.DataSample {
	if u == nil {
		return shared.DataSample{}
	}
	return u.DataSample
}

// UpdateDataSampleByIDResponseBody - a list of DataSample objects
type UpdateDataSampleByIDResponseBody struct {
	Items []shared.DataSample `json:"items,omitempty"`
}

func (u *UpdateDataSampleByIDResponseBody) GetItems() []shared.DataSample {
	if u == nil {
		return nil
	}
	return u.Items
}

type UpdateDataSampleByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of DataSample objects
	Object *UpdateDataSampleByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (u *UpdateDataSampleByIDResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateDataSampleByIDResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateDataSampleByIDResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateDataSampleByIDResponse) GetObject() *UpdateDataSampleByIDResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}

func (u *UpdateDataSampleByIDResponse) GetError() *shared.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
