// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type UpdateDefaultLakeLakehouseByIDRequest struct {
	// The ID of the lakehouse to update
	ID        string           `pathParam:"style=simple,explode=false,name=id"`
	Lakehouse shared.Lakehouse `request:"mediaType=application/json"`
}

func (o *UpdateDefaultLakeLakehouseByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateDefaultLakeLakehouseByIDRequest) GetLakehouse() shared.Lakehouse {
	if o == nil {
		return shared.Lakehouse{}
	}
	return o.Lakehouse
}

// UpdateDefaultLakeLakehouseByIDResponseBody - a list of Lakehouse objects
type UpdateDefaultLakeLakehouseByIDResponseBody struct {
	Items []shared.Lakehouse `json:"items,omitempty"`
}

func (o *UpdateDefaultLakeLakehouseByIDResponseBody) GetItems() []shared.Lakehouse {
	if o == nil {
		return nil
	}
	return o.Items
}

type UpdateDefaultLakeLakehouseByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Lakehouse objects
	Object *UpdateDefaultLakeLakehouseByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *UpdateDefaultLakeLakehouseByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateDefaultLakeLakehouseByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateDefaultLakeLakehouseByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateDefaultLakeLakehouseByIDResponse) GetObject() *UpdateDefaultLakeLakehouseByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *UpdateDefaultLakeLakehouseByIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
