// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type UpdateLookupFileByIDRequest struct {
	// Unique ID to PATCH
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The consumer group to which this instance belongs. Defaults to 'Cribl'.
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
	// LookupFile object to be updated
	LookupFile shared.LookupFile `request:"mediaType=application/json"`
}

func (o *UpdateLookupFileByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateLookupFileByIDRequest) GetGroupID() string {
	if o == nil {
		return ""
	}
	return o.GroupID
}

func (o *UpdateLookupFileByIDRequest) GetLookupFile() shared.LookupFile {
	if o == nil {
		return shared.LookupFile{}
	}
	return o.LookupFile
}

// UpdateLookupFileByIDResponseBody - a list of LookupFile objects
type UpdateLookupFileByIDResponseBody struct {
}

type UpdateLookupFileByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of LookupFile objects
	Object *UpdateLookupFileByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *UpdateLookupFileByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateLookupFileByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateLookupFileByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateLookupFileByIDResponse) GetObject() *UpdateLookupFileByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *UpdateLookupFileByIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
