// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

var V1WorkspacesGetWorkspaceServerList = []string{
	"https://gateway.cribl.cloud",
}

type V1WorkspacesGetWorkspaceRequest struct {
	// Organization identifier
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// Workspace identifier
	WorkspaceID string `pathParam:"style=simple,explode=false,name=workspaceId"`
}

func (v *V1WorkspacesGetWorkspaceRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V1WorkspacesGetWorkspaceRequest) GetWorkspaceID() string {
	if v == nil {
		return ""
	}
	return v.WorkspaceID
}

type V1WorkspacesGetWorkspaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The workspace details have been successfully retrieved
	WorkspaceSchema *shared.WorkspaceSchema
}

func (v *V1WorkspacesGetWorkspaceResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V1WorkspacesGetWorkspaceResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V1WorkspacesGetWorkspaceResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V1WorkspacesGetWorkspaceResponse) GetWorkspaceSchema() *shared.WorkspaceSchema {
	if v == nil {
		return nil
	}
	return v.WorkspaceSchema
}
