// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdk

import (
	"github.com/speakeasy/terraform-provider-criblio/internal/sdk/internal/config"
	"github.com/speakeasy/terraform-provider-criblio/internal/sdk/internal/hooks"
)

type V5Billing struct {
	Consumption *Consumption
	Invoices    *Invoices

	rootSDK          *CriblIo
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newV5Billing(rootSDK *CriblIo, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *V5Billing {
	return &V5Billing{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
		Consumption:      newConsumption(rootSDK, sdkConfig, hooks),
		Invoices:         newInvoices(rootSDK, sdkConfig, hooks),
	}
}
