// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type BannerType string

const (
	BannerTypeCustom BannerType = "custom"
	BannerTypeSystem BannerType = "system"
)

func (e BannerType) ToPointer() *BannerType {
	return &e
}
func (e *BannerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "custom":
		fallthrough
	case "system":
		*e = BannerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BannerType: %v", v)
	}
}

type BannerMessage struct {
	ID *string `json:"id,omitempty"`
	// Show a banner on top of all pages
	Enabled bool       `json:"enabled"`
	Type    BannerType `json:"type"`
	// Time created
	Created         *float64 `json:"created,omitempty"`
	Theme           string   `json:"theme"`
	InvertFontColor *bool    `json:"invertFontColor,omitempty"`
	// Enter a message to display to all your Organization's users, across all Cribl products. Limited to one line and 100 characters; will be truncated as needed.
	Message string `json:"message"`
	// Optionally, provide a URL to append to the message
	Link *string `json:"link,omitempty"`
	// Optionally, display your link with a short text label instead of the raw URL (100-character limit)
	LinkDisplay  *string  `json:"linkDisplay,omitempty"`
	CustomThemes []string `json:"customThemes,omitempty"`
}

func (b *BannerMessage) GetID() *string {
	if b == nil {
		return nil
	}
	return b.ID
}

func (b *BannerMessage) GetEnabled() bool {
	if b == nil {
		return false
	}
	return b.Enabled
}

func (b *BannerMessage) GetType() BannerType {
	if b == nil {
		return BannerType("")
	}
	return b.Type
}

func (b *BannerMessage) GetCreated() *float64 {
	if b == nil {
		return nil
	}
	return b.Created
}

func (b *BannerMessage) GetTheme() string {
	if b == nil {
		return ""
	}
	return b.Theme
}

func (b *BannerMessage) GetInvertFontColor() *bool {
	if b == nil {
		return nil
	}
	return b.InvertFontColor
}

func (b *BannerMessage) GetMessage() string {
	if b == nil {
		return ""
	}
	return b.Message
}

func (b *BannerMessage) GetLink() *string {
	if b == nil {
		return nil
	}
	return b.Link
}

func (b *BannerMessage) GetLinkDisplay() *string {
	if b == nil {
		return nil
	}
	return b.LinkDisplay
}

func (b *BannerMessage) GetCustomThemes() []string {
	if b == nil {
		return nil
	}
	return b.CustomThemes
}
