// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type CloudProvider string

const (
	CloudProviderAws   CloudProvider = "aws"
	CloudProviderAzure CloudProvider = "azure"
)

func (e CloudProvider) ToPointer() *CloudProvider {
	return &e
}
func (e *CloudProvider) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "aws":
		fallthrough
	case "azure":
		*e = CloudProvider(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CloudProvider: %v", v)
	}
}
