// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ContainerPort struct {
	PrivatePort float64 `json:"privatePort"`
	PublicPort  float64 `json:"publicPort"`
}

func (c *ContainerPort) GetPrivatePort() float64 {
	if c == nil {
		return 0.0
	}
	return c.PrivatePort
}

func (c *ContainerPort) GetPublicPort() float64 {
	if c == nil {
		return 0.0
	}
	return c.PublicPort
}
