// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DockerGraphDriver struct {
	Data *DockerGraphDriverData `json:"Data,omitempty"`
}

func (d *DockerGraphDriver) GetData() *DockerGraphDriverData {
	if d == nil {
		return nil
	}
	return d.Data
}
