// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetCreditsDTO struct {
	TotalCreditsPurchased float64    `json:"totalCreditsPurchased"`
	TotalCreditsUsed      float64    `json:"totalCreditsUsed"`
	TotalCreditsAvailable float64    `json:"totalCreditsAvailable"`
	Breakdown             *Breakdown `json:"breakdown,omitempty"`
}

func (o *GetCreditsDTO) GetTotalCreditsPurchased() float64 {
	if o == nil {
		return 0.0
	}
	return o.TotalCreditsPurchased
}

func (o *GetCreditsDTO) GetTotalCreditsUsed() float64 {
	if o == nil {
		return 0.0
	}
	return o.TotalCreditsUsed
}

func (o *GetCreditsDTO) GetTotalCreditsAvailable() float64 {
	if o == nil {
		return 0.0
	}
	return o.TotalCreditsAvailable
}

func (o *GetCreditsDTO) GetBreakdown() *Breakdown {
	if o == nil {
		return nil
	}
	return o.Breakdown
}
