// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/terraform-provider-criblio/internal/sdk/internal/utils"
)

type InputCollectorSplunkTypeCollection1 string

const (
	InputCollectorSplunkTypeCollection1Collection InputCollectorSplunkTypeCollection1 = "collection"
)

func (e InputCollectorSplunkTypeCollection1) ToPointer() *InputCollectorSplunkTypeCollection1 {
	return &e
}
func (e *InputCollectorSplunkTypeCollection1) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "collection":
		*e = InputCollectorSplunkTypeCollection1(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputCollectorSplunkTypeCollection1: %v", v)
	}
}

// InputCollectorSplunkSavedState - Saved state for the collector
type InputCollectorSplunkSavedState struct {
}

func (i InputCollectorSplunkSavedState) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputCollectorSplunkSavedState) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

// InputCollectorSplunkLogLevel - Level at which to set task logging
type InputCollectorSplunkLogLevel string

const (
	InputCollectorSplunkLogLevelError InputCollectorSplunkLogLevel = "error"
	InputCollectorSplunkLogLevelWarn  InputCollectorSplunkLogLevel = "warn"
	InputCollectorSplunkLogLevelInfo  InputCollectorSplunkLogLevel = "info"
	InputCollectorSplunkLogLevelDebug InputCollectorSplunkLogLevel = "debug"
	InputCollectorSplunkLogLevelSilly InputCollectorSplunkLogLevel = "silly"
)

func (e InputCollectorSplunkLogLevel) ToPointer() *InputCollectorSplunkLogLevel {
	return &e
}
func (e *InputCollectorSplunkLogLevel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "error":
		fallthrough
	case "warn":
		fallthrough
	case "info":
		fallthrough
	case "debug":
		fallthrough
	case "silly":
		*e = InputCollectorSplunkLogLevel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputCollectorSplunkLogLevel: %v", v)
	}
}

// InputCollectorSplunkMode - Job run mode. Preview will either return up to N matching results, or will run until capture time T is reached. Discovery will gather the list of files to turn into streaming tasks, without running the data collection job. Full Run will run the collection job.
type InputCollectorSplunkMode string

const (
	InputCollectorSplunkModeList    InputCollectorSplunkMode = "list"
	InputCollectorSplunkModePreview InputCollectorSplunkMode = "preview"
	InputCollectorSplunkModeRun     InputCollectorSplunkMode = "run"
)

func (e InputCollectorSplunkMode) ToPointer() *InputCollectorSplunkMode {
	return &e
}
func (e *InputCollectorSplunkMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		fallthrough
	case "preview":
		fallthrough
	case "run":
		*e = InputCollectorSplunkMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputCollectorSplunkMode: %v", v)
	}
}

type InputCollectorSplunkTimeRange string

const (
	InputCollectorSplunkTimeRangeRelative InputCollectorSplunkTimeRange = "relative"
	InputCollectorSplunkTimeRangeAbsolute InputCollectorSplunkTimeRange = "absolute"
)

func (e InputCollectorSplunkTimeRange) ToPointer() *InputCollectorSplunkTimeRange {
	return &e
}
func (e *InputCollectorSplunkTimeRange) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "relative":
		fallthrough
	case "absolute":
		*e = InputCollectorSplunkTimeRange(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputCollectorSplunkTimeRange: %v", v)
	}
}

// InputCollectorSplunkTimeWarning - Time warning configuration
type InputCollectorSplunkTimeWarning struct {
}

func (i InputCollectorSplunkTimeWarning) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputCollectorSplunkTimeWarning) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

// InputCollectorSplunkStateTracking - State tracking configuration
type InputCollectorSplunkStateTracking struct {
	StateUpdateExpression *string `json:"stateUpdateExpression,omitempty"`
	StateMergeExpression  *string `json:"stateMergeExpression,omitempty"`
	Enabled               *bool   `default:"false" json:"enabled"`
}

func (i InputCollectorSplunkStateTracking) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputCollectorSplunkStateTracking) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *InputCollectorSplunkStateTracking) GetStateUpdateExpression() *string {
	if o == nil {
		return nil
	}
	return o.StateUpdateExpression
}

func (o *InputCollectorSplunkStateTracking) GetStateMergeExpression() *string {
	if o == nil {
		return nil
	}
	return o.StateMergeExpression
}

func (o *InputCollectorSplunkStateTracking) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

type InputCollectorSplunkRunSettings struct {
	// Reschedule tasks that failed with non-fatal errors
	RescheduleDroppedTasks *bool `default:"true" json:"rescheduleDroppedTasks"`
	// Maximum number of times a task can be rescheduled
	MaxTaskReschedule *float64 `default:"1" json:"maxTaskReschedule"`
	// Level at which to set task logging
	LogLevel *InputCollectorSplunkLogLevel `default:"info" json:"logLevel"`
	// Maximum time the job is allowed to run. Time unit defaults to seconds if not specified (examples: 30, 45s, 15m). Enter 0 for unlimited time.
	JobTimeout *string `default:"0" json:"jobTimeout"`
	// Job run mode. Preview will either return up to N matching results, or will run until capture time T is reached. Discovery will gather the list of files to turn into streaming tasks, without running the data collection job. Full Run will run the collection job.
	Mode          *InputCollectorSplunkMode      `default:"list" json:"mode"`
	TimeRangeType *InputCollectorSplunkTimeRange `default:"relative" json:"timeRangeType"`
	// Earliest time to collect data for the selected timezone
	Earliest *float64 `default:"0" json:"earliest"`
	// Latest time to collect data for the selected timezone
	Latest *float64 `default:"1" json:"latest"`
	// A filter for tokens in the provided collect path and/or the events being collected
	Expression *string `default:"true" json:"expression"`
	// Limits the bundle size for small tasks. For example, if your lower bundle size is 1MB, you can bundle up to five 200KB files into one task.
	MinTaskSize *string `default:"1MB" json:"minTaskSize"`
	// Limits the bundle size for files above the lower task bundle size. For example, if your upper bundle size is 10MB, you can bundle up to five 2MB files into one task. Files greater than this size will be assigned to individual tasks.
	MaxTaskSize *string `default:"10MB" json:"maxTaskSize"`
	// Time warning configuration
	TimeWarning *InputCollectorSplunkTimeWarning `json:"timeWarning,omitempty"`
	// State tracking configuration
	StateTracking *InputCollectorSplunkStateTracking `json:"stateTracking,omitempty"`
}

func (i InputCollectorSplunkRunSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputCollectorSplunkRunSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *InputCollectorSplunkRunSettings) GetRescheduleDroppedTasks() *bool {
	if o == nil {
		return nil
	}
	return o.RescheduleDroppedTasks
}

func (o *InputCollectorSplunkRunSettings) GetMaxTaskReschedule() *float64 {
	if o == nil {
		return nil
	}
	return o.MaxTaskReschedule
}

func (o *InputCollectorSplunkRunSettings) GetLogLevel() *InputCollectorSplunkLogLevel {
	if o == nil {
		return nil
	}
	return o.LogLevel
}

func (o *InputCollectorSplunkRunSettings) GetJobTimeout() *string {
	if o == nil {
		return nil
	}
	return o.JobTimeout
}

func (o *InputCollectorSplunkRunSettings) GetMode() *InputCollectorSplunkMode {
	if o == nil {
		return nil
	}
	return o.Mode
}

func (o *InputCollectorSplunkRunSettings) GetTimeRangeType() *InputCollectorSplunkTimeRange {
	if o == nil {
		return nil
	}
	return o.TimeRangeType
}

func (o *InputCollectorSplunkRunSettings) GetEarliest() *float64 {
	if o == nil {
		return nil
	}
	return o.Earliest
}

func (o *InputCollectorSplunkRunSettings) GetLatest() *float64 {
	if o == nil {
		return nil
	}
	return o.Latest
}

func (o *InputCollectorSplunkRunSettings) GetExpression() *string {
	if o == nil {
		return nil
	}
	return o.Expression
}

func (o *InputCollectorSplunkRunSettings) GetMinTaskSize() *string {
	if o == nil {
		return nil
	}
	return o.MinTaskSize
}

func (o *InputCollectorSplunkRunSettings) GetMaxTaskSize() *string {
	if o == nil {
		return nil
	}
	return o.MaxTaskSize
}

func (o *InputCollectorSplunkRunSettings) GetTimeWarning() *InputCollectorSplunkTimeWarning {
	if o == nil {
		return nil
	}
	return o.TimeWarning
}

func (o *InputCollectorSplunkRunSettings) GetStateTracking() *InputCollectorSplunkStateTracking {
	if o == nil {
		return nil
	}
	return o.StateTracking
}

// InputCollectorSplunkSchedule - Configuration for a scheduled job
type InputCollectorSplunkSchedule struct {
	// Enable to configure scheduling for this Collector
	Enabled *bool `json:"enabled,omitempty"`
	// A cron schedule on which to run this job
	CronSchedule *string `default:"*/5 * * * *" json:"cronSchedule"`
	// The maximum number of instances of this scheduled job that may be running at any time
	MaxConcurrentRuns *float64 `default:"1" json:"maxConcurrentRuns"`
	// Skippable jobs can be delayed, up to their next run time, if the system is hitting concurrency limits
	Skippable *bool `default:"true" json:"skippable"`
	// Resume missed scheduled runs
	ResumeMissed *bool                            `default:"false" json:"resumeMissed"`
	Run          *InputCollectorSplunkRunSettings `json:"run,omitempty"`
}

func (i InputCollectorSplunkSchedule) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputCollectorSplunkSchedule) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *InputCollectorSplunkSchedule) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *InputCollectorSplunkSchedule) GetCronSchedule() *string {
	if o == nil {
		return nil
	}
	return o.CronSchedule
}

func (o *InputCollectorSplunkSchedule) GetMaxConcurrentRuns() *float64 {
	if o == nil {
		return nil
	}
	return o.MaxConcurrentRuns
}

func (o *InputCollectorSplunkSchedule) GetSkippable() *bool {
	if o == nil {
		return nil
	}
	return o.Skippable
}

func (o *InputCollectorSplunkSchedule) GetResumeMissed() *bool {
	if o == nil {
		return nil
	}
	return o.ResumeMissed
}

func (o *InputCollectorSplunkSchedule) GetRun() *InputCollectorSplunkRunSettings {
	if o == nil {
		return nil
	}
	return o.Run
}

type InputCollectorSplunkTypeCollection2 string

const (
	InputCollectorSplunkTypeCollection2Collection InputCollectorSplunkTypeCollection2 = "collection"
)

func (e InputCollectorSplunkTypeCollection2) ToPointer() *InputCollectorSplunkTypeCollection2 {
	return &e
}
func (e *InputCollectorSplunkTypeCollection2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "collection":
		*e = InputCollectorSplunkTypeCollection2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputCollectorSplunkTypeCollection2: %v", v)
	}
}

type InputCollectorSplunkPreprocess struct {
	Disabled *bool `default:"true" json:"disabled"`
	// Command to feed the data through (via stdin) and process its output (stdout)
	Command *string `json:"command,omitempty"`
	// Arguments to be added to the custom command
	Args []string `json:"args,omitempty"`
}

func (i InputCollectorSplunkPreprocess) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputCollectorSplunkPreprocess) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *InputCollectorSplunkPreprocess) GetDisabled() *bool {
	if o == nil {
		return nil
	}
	return o.Disabled
}

func (o *InputCollectorSplunkPreprocess) GetCommand() *string {
	if o == nil {
		return nil
	}
	return o.Command
}

func (o *InputCollectorSplunkPreprocess) GetArgs() []string {
	if o == nil {
		return nil
	}
	return o.Args
}

type InputCollectorSplunkMetadatum struct {
	Name string `json:"name"`
	// JavaScript expression to compute field's value, enclosed in quotes or backticks. (Can evaluate to a constant.)
	Value string `json:"value"`
}

func (i InputCollectorSplunkMetadatum) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputCollectorSplunkMetadatum) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"name", "value"}); err != nil {
		return err
	}
	return nil
}

func (o *InputCollectorSplunkMetadatum) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *InputCollectorSplunkMetadatum) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}

type InputCollectorSplunkInput struct {
	Type *InputCollectorSplunkTypeCollection2 `default:"collection" json:"type"`
	// A list of event-breaking rulesets that will be applied, in order, to the input data stream
	BreakerRulesets []string `json:"breakerRulesets,omitempty"`
	// How long (in milliseconds) the Event Breaker will wait for new data to be sent to a specific channel before flushing the data stream out, as is, to the Pipelines
	StaleChannelFlushMs *float64 `default:"10000" json:"staleChannelFlushMs"`
	// Send events to normal routing and event processing. Disable to select a specific Pipeline/Destination combination.
	SendToRoutes *bool                           `default:"true" json:"sendToRoutes"`
	Preprocess   *InputCollectorSplunkPreprocess `json:"preprocess,omitempty"`
	// Rate (in bytes per second) to throttle while writing to an output. Accepts values with multiple-byte units, such as KB, MB, and GB. (Example: 42 MB) Default value of 0 specifies no throttling.
	ThrottleRatePerSec *string `default:"0" json:"throttleRatePerSec"`
	// Fields to add to events from this input
	Metadata []InputCollectorSplunkMetadatum `json:"metadata,omitempty"`
	// Pipeline to process results
	Pipeline *string `json:"pipeline,omitempty"`
	// Destination to send results to
	Output *string `json:"output,omitempty"`
}

func (i InputCollectorSplunkInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputCollectorSplunkInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *InputCollectorSplunkInput) GetType() *InputCollectorSplunkTypeCollection2 {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *InputCollectorSplunkInput) GetBreakerRulesets() []string {
	if o == nil {
		return nil
	}
	return o.BreakerRulesets
}

func (o *InputCollectorSplunkInput) GetStaleChannelFlushMs() *float64 {
	if o == nil {
		return nil
	}
	return o.StaleChannelFlushMs
}

func (o *InputCollectorSplunkInput) GetSendToRoutes() *bool {
	if o == nil {
		return nil
	}
	return o.SendToRoutes
}

func (o *InputCollectorSplunkInput) GetPreprocess() *InputCollectorSplunkPreprocess {
	if o == nil {
		return nil
	}
	return o.Preprocess
}

func (o *InputCollectorSplunkInput) GetThrottleRatePerSec() *string {
	if o == nil {
		return nil
	}
	return o.ThrottleRatePerSec
}

func (o *InputCollectorSplunkInput) GetMetadata() []InputCollectorSplunkMetadatum {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *InputCollectorSplunkInput) GetPipeline() *string {
	if o == nil {
		return nil
	}
	return o.Pipeline
}

func (o *InputCollectorSplunkInput) GetOutput() *string {
	if o == nil {
		return nil
	}
	return o.Output
}

type InputCollectorSplunkTypeSplunk string

const (
	InputCollectorSplunkTypeSplunkSplunk InputCollectorSplunkTypeSplunk = "splunk"
)

func (e InputCollectorSplunkTypeSplunk) ToPointer() *InputCollectorSplunkTypeSplunk {
	return &e
}
func (e *InputCollectorSplunkTypeSplunk) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "splunk":
		*e = InputCollectorSplunkTypeSplunk(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputCollectorSplunkTypeSplunk: %v", v)
	}
}

type InputCollectorSplunkOutputMode string

const (
	InputCollectorSplunkOutputModeCsv  InputCollectorSplunkOutputMode = "csv"
	InputCollectorSplunkOutputModeJSON InputCollectorSplunkOutputMode = "json"
)

func (e InputCollectorSplunkOutputMode) ToPointer() *InputCollectorSplunkOutputMode {
	return &e
}
func (e *InputCollectorSplunkOutputMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "csv":
		fallthrough
	case "json":
		*e = InputCollectorSplunkOutputMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputCollectorSplunkOutputMode: %v", v)
	}
}

type InputCollectorSplunkAuthentication string

const (
	InputCollectorSplunkAuthenticationNone              InputCollectorSplunkAuthentication = "none"
	InputCollectorSplunkAuthenticationBasic             InputCollectorSplunkAuthentication = "basic"
	InputCollectorSplunkAuthenticationBasicSecret       InputCollectorSplunkAuthentication = "basicSecret"
	InputCollectorSplunkAuthenticationToken             InputCollectorSplunkAuthentication = "token"
	InputCollectorSplunkAuthenticationTokenSecret       InputCollectorSplunkAuthentication = "tokenSecret"
	InputCollectorSplunkAuthenticationLogin             InputCollectorSplunkAuthentication = "login"
	InputCollectorSplunkAuthenticationLoginSecret       InputCollectorSplunkAuthentication = "loginSecret"
	InputCollectorSplunkAuthenticationOauth             InputCollectorSplunkAuthentication = "oauth"
	InputCollectorSplunkAuthenticationOauthSecret       InputCollectorSplunkAuthentication = "oauthSecret"
	InputCollectorSplunkAuthenticationGoogleOauth       InputCollectorSplunkAuthentication = "google_oauth"
	InputCollectorSplunkAuthenticationGoogleOauthSecret InputCollectorSplunkAuthentication = "google_oauthSecret"
	InputCollectorSplunkAuthenticationHmac              InputCollectorSplunkAuthentication = "hmac"
)

func (e InputCollectorSplunkAuthentication) ToPointer() *InputCollectorSplunkAuthentication {
	return &e
}
func (e *InputCollectorSplunkAuthentication) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "none":
		fallthrough
	case "basic":
		fallthrough
	case "basicSecret":
		fallthrough
	case "token":
		fallthrough
	case "tokenSecret":
		fallthrough
	case "login":
		fallthrough
	case "loginSecret":
		fallthrough
	case "oauth":
		fallthrough
	case "oauthSecret":
		fallthrough
	case "google_oauth":
		fallthrough
	case "google_oauthSecret":
		fallthrough
	case "hmac":
		*e = InputCollectorSplunkAuthentication(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputCollectorSplunkAuthentication: %v", v)
	}
}

type InputCollectorSplunkConf struct {
	// Search head base URL
	SearchHead *string `json:"searchHead,omitempty"`
	// Splunk search query
	Search *string `json:"search,omitempty"`
	// Earliest time boundary for the search
	Earliest *string `json:"earliest,omitempty"`
	// Latest time boundary for the search
	Latest *string `json:"latest,omitempty"`
	// REST API endpoint used to create a search
	Endpoint           *string                             `json:"endpoint,omitempty"`
	OutputMode         *InputCollectorSplunkOutputMode     `json:"outputMode,omitempty"`
	Authentication     *InputCollectorSplunkAuthentication `json:"authentication,omitempty"`
	Timeout            *int64                              `json:"timeout,omitempty"`
	UseRoundRobinDNS   *bool                               `json:"useRoundRobinDns,omitempty"`
	DisableTimeFilter  *bool                               `json:"disableTimeFilter,omitempty"`
	RejectUnauthorized *bool                               `json:"rejectUnauthorized,omitempty"`
	HandleEscapedChars *bool                               `json:"handleEscapedChars,omitempty"`
	Username           *string                             `json:"username,omitempty"`
	Password           *string                             `json:"password,omitempty"`
	CredentialsSecret  *string                             `json:"credentialsSecret,omitempty"`
	Token              *string                             `json:"token,omitempty"`
	TokenSecret        *string                             `json:"tokenSecret,omitempty"`
}

func (i InputCollectorSplunkConf) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputCollectorSplunkConf) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *InputCollectorSplunkConf) GetSearchHead() *string {
	if o == nil {
		return nil
	}
	return o.SearchHead
}

func (o *InputCollectorSplunkConf) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}

func (o *InputCollectorSplunkConf) GetEarliest() *string {
	if o == nil {
		return nil
	}
	return o.Earliest
}

func (o *InputCollectorSplunkConf) GetLatest() *string {
	if o == nil {
		return nil
	}
	return o.Latest
}

func (o *InputCollectorSplunkConf) GetEndpoint() *string {
	if o == nil {
		return nil
	}
	return o.Endpoint
}

func (o *InputCollectorSplunkConf) GetOutputMode() *InputCollectorSplunkOutputMode {
	if o == nil {
		return nil
	}
	return o.OutputMode
}

func (o *InputCollectorSplunkConf) GetAuthentication() *InputCollectorSplunkAuthentication {
	if o == nil {
		return nil
	}
	return o.Authentication
}

func (o *InputCollectorSplunkConf) GetTimeout() *int64 {
	if o == nil {
		return nil
	}
	return o.Timeout
}

func (o *InputCollectorSplunkConf) GetUseRoundRobinDNS() *bool {
	if o == nil {
		return nil
	}
	return o.UseRoundRobinDNS
}

func (o *InputCollectorSplunkConf) GetDisableTimeFilter() *bool {
	if o == nil {
		return nil
	}
	return o.DisableTimeFilter
}

func (o *InputCollectorSplunkConf) GetRejectUnauthorized() *bool {
	if o == nil {
		return nil
	}
	return o.RejectUnauthorized
}

func (o *InputCollectorSplunkConf) GetHandleEscapedChars() *bool {
	if o == nil {
		return nil
	}
	return o.HandleEscapedChars
}

func (o *InputCollectorSplunkConf) GetUsername() *string {
	if o == nil {
		return nil
	}
	return o.Username
}

func (o *InputCollectorSplunkConf) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

func (o *InputCollectorSplunkConf) GetCredentialsSecret() *string {
	if o == nil {
		return nil
	}
	return o.CredentialsSecret
}

func (o *InputCollectorSplunkConf) GetToken() *string {
	if o == nil {
		return nil
	}
	return o.Token
}

func (o *InputCollectorSplunkConf) GetTokenSecret() *string {
	if o == nil {
		return nil
	}
	return o.TokenSecret
}

type InputCollectorSplunkCollector struct {
	Type InputCollectorSplunkTypeSplunk `json:"type"`
	Conf *InputCollectorSplunkConf      `json:"conf,omitempty"`
}

func (i InputCollectorSplunkCollector) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputCollectorSplunkCollector) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (o *InputCollectorSplunkCollector) GetType() InputCollectorSplunkTypeSplunk {
	if o == nil {
		return InputCollectorSplunkTypeSplunk("")
	}
	return o.Type
}

func (o *InputCollectorSplunkCollector) GetConf() *InputCollectorSplunkConf {
	if o == nil {
		return nil
	}
	return o.Conf
}

type InputCollectorSplunk struct {
	ID                   *string                              `json:"id,omitempty"`
	Type                 *InputCollectorSplunkTypeCollection1 `default:"collection" json:"type"`
	TTL                  *string                              `default:"4h" json:"ttl"`
	IgnoreGroupJobsLimit *bool                                `default:"false" json:"ignoreGroupJobsLimit"`
	RemoveFields         []string                             `json:"removeFields,omitempty"`
	ResumeOnBoot         *bool                                `default:"true" json:"resumeOnBoot"`
	Environment          *string                              `json:"environment,omitempty"`
	// Saved state for the collector
	SavedState *InputCollectorSplunkSavedState `json:"savedState,omitempty"`
	// Configuration for a scheduled job
	Schedule *InputCollectorSplunkSchedule `json:"schedule,omitempty"`
	// Tags for filtering and grouping
	Streamtags []string `json:"streamtags,omitempty"`
	// If enabled, tasks are created and run by the same Worker Node
	WorkerAffinity *bool                         `default:"false" json:"workerAffinity"`
	Input          *InputCollectorSplunkInput    `json:"input,omitempty"`
	Collector      InputCollectorSplunkCollector `json:"collector"`
}

func (i InputCollectorSplunk) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputCollectorSplunk) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"collector"}); err != nil {
		return err
	}
	return nil
}

func (o *InputCollectorSplunk) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *InputCollectorSplunk) GetType() *InputCollectorSplunkTypeCollection1 {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *InputCollectorSplunk) GetTTL() *string {
	if o == nil {
		return nil
	}
	return o.TTL
}

func (o *InputCollectorSplunk) GetIgnoreGroupJobsLimit() *bool {
	if o == nil {
		return nil
	}
	return o.IgnoreGroupJobsLimit
}

func (o *InputCollectorSplunk) GetRemoveFields() []string {
	if o == nil {
		return nil
	}
	return o.RemoveFields
}

func (o *InputCollectorSplunk) GetResumeOnBoot() *bool {
	if o == nil {
		return nil
	}
	return o.ResumeOnBoot
}

func (o *InputCollectorSplunk) GetEnvironment() *string {
	if o == nil {
		return nil
	}
	return o.Environment
}

func (o *InputCollectorSplunk) GetSavedState() *InputCollectorSplunkSavedState {
	if o == nil {
		return nil
	}
	return o.SavedState
}

func (o *InputCollectorSplunk) GetSchedule() *InputCollectorSplunkSchedule {
	if o == nil {
		return nil
	}
	return o.Schedule
}

func (o *InputCollectorSplunk) GetStreamtags() []string {
	if o == nil {
		return nil
	}
	return o.Streamtags
}

func (o *InputCollectorSplunk) GetWorkerAffinity() *bool {
	if o == nil {
		return nil
	}
	return o.WorkerAffinity
}

func (o *InputCollectorSplunk) GetInput() *InputCollectorSplunkInput {
	if o == nil {
		return nil
	}
	return o.Input
}

func (o *InputCollectorSplunk) GetCollector() InputCollectorSplunkCollector {
	if o == nil {
		return InputCollectorSplunkCollector{}
	}
	return o.Collector
}
