// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type LastMetrics struct {
}

type MasterWorkerEntryType string

const (
	MasterWorkerEntryTypeInfo MasterWorkerEntryType = "info"
	MasterWorkerEntryTypeReq  MasterWorkerEntryType = "req"
	MasterWorkerEntryTypeResp MasterWorkerEntryType = "resp"
)

func (e MasterWorkerEntryType) ToPointer() *MasterWorkerEntryType {
	return &e
}
func (e *MasterWorkerEntryType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "info":
		fallthrough
	case "req":
		fallthrough
	case "resp":
		*e = MasterWorkerEntryType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MasterWorkerEntryType: %v", v)
	}
}

type MasterWorkerEntryWorkers struct {
	Count float64 `json:"count"`
}

func (m *MasterWorkerEntryWorkers) GetCount() float64 {
	if m == nil {
		return 0.0
	}
	return m.Count
}

type MasterWorkerEntry struct {
	Deployable        *bool                     `json:"deployable,omitempty"`
	FirstMsgTime      float64                   `json:"firstMsgTime"`
	Group             string                    `json:"group"`
	ID                string                    `json:"id"`
	Info              NodeProvidedInfo          `json:"info"`
	LastMetrics       *LastMetrics              `json:"lastMetrics,omitempty"`
	LastMsgTime       float64                   `json:"lastMsgTime"`
	Metadata          *HeartbeatMetadata        `json:"metadata,omitempty"`
	NodeUpgradeStatus *NodeUpgradeStatus        `json:"nodeUpgradeStatus,omitempty"`
	Status            *string                   `json:"status,omitempty"`
	Type              *MasterWorkerEntryType    `json:"type,omitempty"`
	WorkerProcesses   float64                   `json:"workerProcesses"`
	Workers           *MasterWorkerEntryWorkers `json:"workers,omitempty"`
}

func (m *MasterWorkerEntry) GetDeployable() *bool {
	if m == nil {
		return nil
	}
	return m.Deployable
}

func (m *MasterWorkerEntry) GetFirstMsgTime() float64 {
	if m == nil {
		return 0.0
	}
	return m.FirstMsgTime
}

func (m *MasterWorkerEntry) GetGroup() string {
	if m == nil {
		return ""
	}
	return m.Group
}

func (m *MasterWorkerEntry) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *MasterWorkerEntry) GetInfo() NodeProvidedInfo {
	if m == nil {
		return NodeProvidedInfo{}
	}
	return m.Info
}

func (m *MasterWorkerEntry) GetLastMetrics() *LastMetrics {
	if m == nil {
		return nil
	}
	return m.LastMetrics
}

func (m *MasterWorkerEntry) GetLastMsgTime() float64 {
	if m == nil {
		return 0.0
	}
	return m.LastMsgTime
}

func (m *MasterWorkerEntry) GetMetadata() *HeartbeatMetadata {
	if m == nil {
		return nil
	}
	return m.Metadata
}

func (m *MasterWorkerEntry) GetNodeUpgradeStatus() *NodeUpgradeStatus {
	if m == nil {
		return nil
	}
	return m.NodeUpgradeStatus
}

func (m *MasterWorkerEntry) GetStatus() *string {
	if m == nil {
		return nil
	}
	return m.Status
}

func (m *MasterWorkerEntry) GetType() *MasterWorkerEntryType {
	if m == nil {
		return nil
	}
	return m.Type
}

func (m *MasterWorkerEntry) GetWorkerProcesses() float64 {
	if m == nil {
		return 0.0
	}
	return m.WorkerProcesses
}

func (m *MasterWorkerEntry) GetWorkers() *MasterWorkerEntryWorkers {
	if m == nil {
		return nil
	}
	return m.Workers
}
