// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PackClone struct {
	Dest       *string  `json:"dest,omitempty"`
	DstGroups  []string `json:"dstGroups"`
	Force      *bool    `json:"force,omitempty"`
	IsDisabled *bool    `json:"isDisabled,omitempty"`
	Packs      []string `json:"packs"`
	SrcGroup   string   `json:"srcGroup"`
}

func (p *PackClone) GetDest() *string {
	if p == nil {
		return nil
	}
	return p.Dest
}

func (p *PackClone) GetDstGroups() []string {
	if p == nil {
		return []string{}
	}
	return p.DstGroups
}

func (p *PackClone) GetForce() *bool {
	if p == nil {
		return nil
	}
	return p.Force
}

func (p *PackClone) GetIsDisabled() *bool {
	if p == nil {
		return nil
	}
	return p.IsDisabled
}

func (p *PackClone) GetPacks() []string {
	if p == nil {
		return []string{}
	}
	return p.Packs
}

func (p *PackClone) GetSrcGroup() string {
	if p == nil {
		return ""
	}
	return p.SrcGroup
}
