// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Process struct {
	ID   string  `json:"id"`
	Pid  float64 `json:"pid"`
	Ppid float64 `json:"ppid"`
}

func (p *Process) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *Process) GetPid() float64 {
	if p == nil {
		return 0.0
	}
	return p.Pid
}

func (p *Process) GetPpid() float64 {
	if p == nil {
		return 0.0
	}
	return p.Ppid
}
