// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Consumers struct {
}

type ProjectConfig struct {
	Consumers     *Consumers `json:"consumers,omitempty"`
	Description   *string    `json:"description,omitempty"`
	Destinations  []string   `json:"destinations"`
	ID            string     `json:"id"`
	Subscriptions []string   `json:"subscriptions"`
}

func (p *ProjectConfig) GetConsumers() *Consumers {
	if p == nil {
		return nil
	}
	return p.Consumers
}

func (p *ProjectConfig) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *ProjectConfig) GetDestinations() []string {
	if p == nil {
		return []string{}
	}
	return p.Destinations
}

func (p *ProjectConfig) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *ProjectConfig) GetSubscriptions() []string {
	if p == nil {
		return []string{}
	}
	return p.Subscriptions
}
