// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ResourcePolicy struct {
	Gid    string       `json:"gid"`
	ID     *string      `json:"id,omitempty"`
	Policy string       `json:"policy"`
	Type   RbacResource `json:"type"`
}

func (r *ResourcePolicy) GetGid() string {
	if r == nil {
		return ""
	}
	return r.Gid
}

func (r *ResourcePolicy) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *ResourcePolicy) GetPolicy() string {
	if r == nil {
		return ""
	}
	return r.Policy
}

func (r *ResourcePolicy) GetType() RbacResource {
	if r == nil {
		return RbacResource("")
	}
	return r.Type
}
