// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RestSecret struct {
	APIKey      *string    `json:"apiKey,omitempty"`
	Description *string    `json:"description,omitempty"`
	ID          string     `json:"id"`
	Password    *string    `json:"password,omitempty"`
	SecretKey   *string    `json:"secretKey,omitempty"`
	SecretType  SecretType `json:"secretType"`
	Tags        *string    `json:"tags,omitempty"`
	Username    *string    `json:"username,omitempty"`
	Value       *string    `json:"value,omitempty"`
}

func (r *RestSecret) GetAPIKey() *string {
	if r == nil {
		return nil
	}
	return r.APIKey
}

func (r *RestSecret) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *RestSecret) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RestSecret) GetPassword() *string {
	if r == nil {
		return nil
	}
	return r.Password
}

func (r *RestSecret) GetSecretKey() *string {
	if r == nil {
		return nil
	}
	return r.SecretKey
}

func (r *RestSecret) GetSecretType() SecretType {
	if r == nil {
		return SecretType("")
	}
	return r.SecretType
}

func (r *RestSecret) GetTags() *string {
	if r == nil {
		return nil
	}
	return r.Tags
}

func (r *RestSecret) GetUsername() *string {
	if r == nil {
		return nil
	}
	return r.Username
}

func (r *RestSecret) GetValue() *string {
	if r == nil {
		return nil
	}
	return r.Value
}
