// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SMTPTargetConfig struct {
	// Email subject
	Subject *string `json:"subject,omitempty"`
	// Email body
	Body           *string         `json:"body,omitempty"`
	EmailRecipient *EmailRecipient `json:"emailRecipient,omitempty"`
}

func (o *SMTPTargetConfig) GetSubject() *string {
	if o == nil {
		return nil
	}
	return o.Subject
}

func (o *SMTPTargetConfig) GetBody() *string {
	if o == nil {
		return nil
	}
	return o.Body
}

func (o *SMTPTargetConfig) GetEmailRecipient() *EmailRecipient {
	if o == nil {
		return nil
	}
	return o.EmailRecipient
}
