// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Package struct {
	// Package HTTP URL or local path
	PackageURL string `json:"packageUrl"`
	// Package's MD5 or SHA256 hash HTTP URL or local path
	PackageHashURL *string `json:"packageHashUrl,omitempty"`
}

func (p *Package) GetPackageURL() string {
	if p == nil {
		return ""
	}
	return p.PackageURL
}

func (p *Package) GetPackageHashURL() *string {
	if p == nil {
		return nil
	}
	return p.PackageHashURL
}

type UpgradeMasterRequest struct {
	// Provide your own URLs or local paths for platform-specific Cribl packages
	Packages []Package `json:"packages,omitempty"`
}

func (u *UpgradeMasterRequest) GetPackages() []Package {
	if u == nil {
		return nil
	}
	return u.Packages
}
