// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type VersionInfo struct {
	Architecture *string  `json:"architecture,omitempty"`
	Build        string   `json:"build"`
	DownloadURL  *string  `json:"downloadUrl,omitempty"`
	FullVersion  string   `json:"fullVersion"`
	Major        float64  `json:"major"`
	Minor        float64  `json:"minor"`
	Platform     *string  `json:"platform,omitempty"`
	Point        *float64 `json:"point,omitempty"`
	PreRelease   *string  `json:"preRelease,omitempty"`
}

func (v *VersionInfo) GetArchitecture() *string {
	if v == nil {
		return nil
	}
	return v.Architecture
}

func (v *VersionInfo) GetBuild() string {
	if v == nil {
		return ""
	}
	return v.Build
}

func (v *VersionInfo) GetDownloadURL() *string {
	if v == nil {
		return nil
	}
	return v.DownloadURL
}

func (v *VersionInfo) GetFullVersion() string {
	if v == nil {
		return ""
	}
	return v.FullVersion
}

func (v *VersionInfo) GetMajor() float64 {
	if v == nil {
		return 0.0
	}
	return v.Major
}

func (v *VersionInfo) GetMinor() float64 {
	if v == nil {
		return 0.0
	}
	return v.Minor
}

func (v *VersionInfo) GetPlatform() *string {
	if v == nil {
		return nil
	}
	return v.Platform
}

func (v *VersionInfo) GetPoint() *float64 {
	if v == nil {
		return nil
	}
	return v.Point
}

func (v *VersionInfo) GetPreRelease() *string {
	if v == nil {
		return nil
	}
	return v.PreRelease
}
