workflowVersion: 1.0.0
speakeasyVersion: 1.638.1
sources:
  Cribl Control Plane and Management API:
    inputs:
      - location: openapi.yml
      - location: openapi-mgmt.yml
    registry:
      location: registry.speakeasyapi.dev/cribl/cribl/cribl-control-plane-and-management-api
targets:
  cribl-io:
    target: terraform
    source: Cribl Control Plane and Management API
    publish:
      terraform:
        gpgPrivateKey: $terraform_gpg_private_key
        gpgPassPhrase: $terraform_gpg_passphrase
