// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *SearchMacroDataSourceModel) RefreshFromSharedSearchMacro(ctx context.Context, resp *shared.SearchMacro) diag.Diagnostics {
	var diags diag.Diagnostics

	r.Created = types.Float64PointerValue(resp.Created)
	r.CreatedBy = types.StringPointerValue(resp.CreatedBy)
	r.Description = types.StringPointerValue(resp.Description)
	r.ID = types.StringValue(resp.ID)
	r.Modified = types.Float64PointerValue(resp.Modified)
	r.Replacement = types.StringValue(resp.Replacement)
	r.Tags = types.StringPointerValue(resp.Tags)

	return diags
}
