// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AppscopeConfigWithCustomFormatNdjson struct {
	Enhancefs      types.Bool    `tfsdk:"enhancefs"`
	Maxeventpersec types.Float64 `tfsdk:"maxeventpersec"`
}
