// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ExtraLogType struct {
	Description types.String `tfsdk:"description"`
	LogType     types.String `tfsdk:"log_type"`
}
