// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Group struct {
	Cloud               *Cloud         `tfsdk:"cloud"`
	EstimatedIngestRate types.Float64  `tfsdk:"estimated_ingest_rate"`
	ID                  types.String   `tfsdk:"id"`
	IsFleet             types.Bool     `tfsdk:"is_fleet"`
	Name                types.String   `tfsdk:"name"`
	OnPrem              types.Bool     `tfsdk:"on_prem"`
	Provisioned         types.Bool     `tfsdk:"provisioned"`
	Streamtags          []types.String `tfsdk:"streamtags"`
	WorkerRemoteAccess  types.Bool     `tfsdk:"worker_remote_access"`
}
