// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type InputS3Checkpointing struct {
	Enabled types.Bool    `tfsdk:"enabled"`
	Retries types.Float64 `tfsdk:"retries"`
}
