// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type InputCollectorHealthCheckSchedule struct {
	CronSchedule      types.String                          `tfsdk:"cron_schedule"`
	Enabled           types.Bool                            `tfsdk:"enabled"`
	MaxConcurrentRuns types.Float64                         `tfsdk:"max_concurrent_runs"`
	ResumeMissed      types.Bool                            `tfsdk:"resume_missed"`
	Run               *InputCollectorHealthCheckRunSettings `tfsdk:"run"`
	Skippable         types.Bool                            `tfsdk:"skippable"`
}
