// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type InputCollectorDatabaseCollector struct {
	Conf *InputCollectorDatabaseConf `tfsdk:"conf"`
	Type types.String                `tfsdk:"type"`
}
