// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type InputWindowsMetrics struct {
	Connections         []ConnectionWindowsMetrics `tfsdk:"connections"`
	Description         types.String               `tfsdk:"description"`
	Disabled            types.Bool                 `tfsdk:"disabled"`
	DisableNativeModule types.Bool                 `tfsdk:"disable_native_module"`
	Environment         types.String               `tfsdk:"environment"`
	Host                *HostWindowsMetrics        `tfsdk:"host"`
	ID                  types.String               `tfsdk:"id"`
	Interval            types.Float64              `tfsdk:"interval"`
	Metadata            []MetadatumWindowsMetrics  `tfsdk:"metadata"`
	Persistence         *PersistenceWindowsMetrics `tfsdk:"persistence"`
	Pipeline            types.String               `tfsdk:"pipeline"`
	Pq                  *PqWindowsMetrics          `tfsdk:"pq"`
	PqEnabled           types.Bool                 `tfsdk:"pq_enabled"`
	Process             *ProcessWindowsMetrics     `tfsdk:"process"`
	SendToRoutes        types.Bool                 `tfsdk:"send_to_routes"`
	Status              *TFStatus                  `tfsdk:"status"`
	Streamtags          []types.String             `tfsdk:"streamtags"`
	Type                types.String               `tfsdk:"type"`
}
