// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type OktaAccountConfig struct {
	APIToken       types.String `tfsdk:"api_token"`
	DomainEndpoint types.String `tfsdk:"domain_endpoint"`
	Name           types.String `tfsdk:"name"`
}
