// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type OutputElasticURL struct {
	URL    types.String  `tfsdk:"url"`
	Weight types.Float64 `tfsdk:"weight"`
}
