// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type OutputElastic struct {
	Auth                          *AuthElastic                   `tfsdk:"auth"`
	Compress                      types.Bool                     `tfsdk:"compress"`
	Concurrency                   types.Float64                  `tfsdk:"concurrency"`
	Description                   types.String                   `tfsdk:"description"`
	DNSResolvePeriodSec           types.Float64                  `tfsdk:"dns_resolve_period_sec"`
	DocType                       types.String                   `tfsdk:"doc_type"`
	ElasticPipeline               types.String                   `tfsdk:"elastic_pipeline"`
	ElasticVersion                types.String                   `tfsdk:"elastic_version"`
	Environment                   types.String                   `tfsdk:"environment"`
	ExcludeSelf                   types.Bool                     `tfsdk:"exclude_self"`
	ExtraHTTPHeaders              []OutputExtraHTTPHeaderElastic `tfsdk:"extra_http_headers"`
	ExtraParams                   []ExtraParamElastic            `tfsdk:"extra_params"`
	FailedRequestLoggingMode      types.String                   `tfsdk:"failed_request_logging_mode"`
	FlushPeriodSec                types.Float64                  `tfsdk:"flush_period_sec"`
	ID                            types.String                   `tfsdk:"id"`
	IncludeDocID                  types.Bool                     `tfsdk:"include_doc_id"`
	Index                         types.String                   `tfsdk:"index"`
	LoadBalanced                  types.Bool                     `tfsdk:"load_balanced"`
	LoadBalanceStatsPeriodSec     types.Float64                  `tfsdk:"load_balance_stats_period_sec"`
	MaxPayloadEvents              types.Float64                  `tfsdk:"max_payload_events"`
	MaxPayloadSizeKB              types.Float64                  `tfsdk:"max_payload_size_kb"`
	OnBackpressure                types.String                   `tfsdk:"on_backpressure"`
	Pipeline                      types.String                   `tfsdk:"pipeline"`
	PqCompress                    types.String                   `tfsdk:"pq_compress"`
	PqControls                    *PqControlsElastic             `tfsdk:"pq_controls"`
	PqMaxFileSize                 types.String                   `tfsdk:"pq_max_file_size"`
	PqMaxSize                     types.String                   `tfsdk:"pq_max_size"`
	PqMode                        types.String                   `tfsdk:"pq_mode"`
	PqOnBackpressure              types.String                   `tfsdk:"pq_on_backpressure"`
	PqPath                        types.String                   `tfsdk:"pq_path"`
	RejectUnauthorized            types.Bool                     `tfsdk:"reject_unauthorized"`
	ResponseHonorRetryAfterHeader types.Bool                     `tfsdk:"response_honor_retry_after_header"`
	ResponseRetrySettings         []ResponseRetrySettingElastic  `tfsdk:"response_retry_settings"`
	RetryPartialErrors            types.Bool                     `tfsdk:"retry_partial_errors"`
	SafeHeaders                   []types.String                 `tfsdk:"safe_headers"`
	Status                        *TFStatus                      `tfsdk:"status"`
	Streamtags                    []types.String                 `tfsdk:"streamtags"`
	SystemFields                  []types.String                 `tfsdk:"system_fields"`
	TimeoutRetrySettings          *TimeoutRetrySettingsElastic   `tfsdk:"timeout_retry_settings"`
	TimeoutSec                    types.Float64                  `tfsdk:"timeout_sec"`
	Type                          types.String                   `tfsdk:"type"`
	URL                           types.String                   `tfsdk:"url"`
	Urls                          []URLElastic                   `tfsdk:"urls"`
	UseRoundRobinDNS              types.Bool                     `tfsdk:"use_round_robin_dns"`
	WriteAction                   types.String                   `tfsdk:"write_action"`
}
