// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type OutputRouter struct {
	Description  types.String       `tfsdk:"description"`
	Environment  types.String       `tfsdk:"environment"`
	ID           types.String       `tfsdk:"id"`
	Pipeline     types.String       `tfsdk:"pipeline"`
	Rules        []OutputRouterRule `tfsdk:"rules"`
	Streamtags   []types.String     `tfsdk:"streamtags"`
	SystemFields []types.String     `tfsdk:"system_fields"`
	Type         types.String       `tfsdk:"type"`
}
