// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type OutputCriblLake struct {
	AddIDToStagePath              types.Bool     `tfsdk:"add_id_to_stage_path"`
	AdditionalProperties          types.String   `tfsdk:"additional_properties"`
	AssumeRoleArn                 types.String   `tfsdk:"assume_role_arn"`
	AssumeRoleExternalID          types.String   `tfsdk:"assume_role_external_id"`
	AwsAuthenticationMethod       types.String   `tfsdk:"aws_authentication_method"`
	AwsSecretKey                  types.String   `tfsdk:"aws_secret_key"`
	BaseFileName                  types.String   `tfsdk:"base_file_name"`
	Bucket                        types.String   `tfsdk:"bucket"`
	DeadletterEnabled             types.Bool     `tfsdk:"deadletter_enabled"`
	DeadletterPath                types.String   `tfsdk:"deadletter_path"`
	Description                   types.String   `tfsdk:"description"`
	DestPath                      types.String   `tfsdk:"dest_path"`
	DurationSeconds               types.Float64  `tfsdk:"duration_seconds"`
	EmptyDirCleanupSec            types.Float64  `tfsdk:"empty_dir_cleanup_sec"`
	EnableAssumeRole              types.Bool     `tfsdk:"enable_assume_role"`
	Endpoint                      types.String   `tfsdk:"endpoint"`
	Environment                   types.String   `tfsdk:"environment"`
	FileNameSuffix                types.String   `tfsdk:"file_name_suffix"`
	Format                        types.String   `tfsdk:"format"`
	HeaderLine                    types.String   `tfsdk:"header_line"`
	ID                            types.String   `tfsdk:"id"`
	KmsKeyID                      types.String   `tfsdk:"kms_key_id"`
	MaxClosingFilesToBackpressure types.Float64  `tfsdk:"max_closing_files_to_backpressure"`
	MaxConcurrentFileParts        types.Float64  `tfsdk:"max_concurrent_file_parts"`
	MaxFileIdleTimeSec            types.Float64  `tfsdk:"max_file_idle_time_sec"`
	MaxFileOpenTimeSec            types.Float64  `tfsdk:"max_file_open_time_sec"`
	MaxFileSizeMB                 types.Float64  `tfsdk:"max_file_size_mb"`
	MaxOpenFiles                  types.Float64  `tfsdk:"max_open_files"`
	MaxRetryNum                   types.Float64  `tfsdk:"max_retry_num"`
	ObjectACL                     types.String   `tfsdk:"object_acl"`
	OnBackpressure                types.String   `tfsdk:"on_backpressure"`
	OnDiskFullBackpressure        types.String   `tfsdk:"on_disk_full_backpressure"`
	Pipeline                      types.String   `tfsdk:"pipeline"`
	Region                        types.String   `tfsdk:"region"`
	RejectUnauthorized            types.Bool     `tfsdk:"reject_unauthorized"`
	RemoveEmptyDirs               types.Bool     `tfsdk:"remove_empty_dirs"`
	ReuseConnections              types.Bool     `tfsdk:"reuse_connections"`
	ServerSideEncryption          types.String   `tfsdk:"server_side_encryption"`
	SignatureVersion              types.String   `tfsdk:"signature_version"`
	StagePath                     types.String   `tfsdk:"stage_path"`
	Status                        *TFStatus      `tfsdk:"status"`
	StorageClass                  types.String   `tfsdk:"storage_class"`
	Streamtags                    []types.String `tfsdk:"streamtags"`
	SystemFields                  []types.String `tfsdk:"system_fields"`
	Type                          types.String   `tfsdk:"type"`
	VerifyPermissions             types.Bool     `tfsdk:"verify_permissions"`
	WriteHighWaterMark            types.Float64  `tfsdk:"write_high_water_mark"`
}
