// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ParserLibEntry struct {
	Description types.String `tfsdk:"description"`
	ID          types.String `tfsdk:"id"`
	Lib         types.String `tfsdk:"lib"`
	Tags        types.String `tfsdk:"tags"`
	Type        types.String `tfsdk:"type"`
}
