// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type S3Provider struct {
	AssumeRoleArn           types.String `tfsdk:"assume_role_arn"`
	AssumeRoleExternalID    types.String `tfsdk:"assume_role_external_id"`
	AwsAPIKey               types.String `tfsdk:"aws_api_key"`
	AwsAuthenticationMethod types.String `tfsdk:"aws_authentication_method"`
	AwsSecretKey            types.String `tfsdk:"aws_secret_key"`
	Bucket                  types.String `tfsdk:"bucket"`
	BucketPathSuggestion    types.String `tfsdk:"bucket_path_suggestion"`
	Description             types.String `tfsdk:"description"`
	EnableAbacTagging       types.Bool   `tfsdk:"enable_abac_tagging"`
	EnableAssumeRole        types.Bool   `tfsdk:"enable_assume_role"`
	Endpoint                types.String `tfsdk:"endpoint"`
	ID                      types.String `tfsdk:"id"`
	Region                  types.String `tfsdk:"region"`
	RejectUnauthorized      types.Bool   `tfsdk:"reject_unauthorized"`
	ReuseConnections        types.Bool   `tfsdk:"reuse_connections"`
	SessionToken            types.String `tfsdk:"session_token"`
	SignatureVersion        types.String `tfsdk:"signature_version"`
	Type                    types.String `tfsdk:"type"`
}
